---
- name: Configure | elasticsearch | http_basic
  lineinfile:
    state: present
    dest: "{{ elasticsearch_config_path }}/elasticsearch.yml"
    regexp: "{{ item.key }}:"
    line: "{{ item.key }}: {{ item.value }}"
  with_items:
    - { key: http.basic.enabled,   value: "{{ elasticsearch_http_basic_enabled }}" }
    - { key: http.basic.user,      value: "{{ elasticsearch_http_basic_user }}" }
    - { key: http.basic.password,  value: "{{ elasticsearch_http_basic_password }}" }
    - { key: http.basic.log,       value: "{{ elasticsearch_http_basic_log }}" }
  notify: Reload Service | elasticsearch
  when: elasticsearch_http_basic_enabled
  tags:
    - configuration
    - elasticsearch

- name: Upload configuration templates | elasticsearch
  template:
    src: elasticsearch.yml
    dest: "{{ elasticsearch_config_path }}/elasticsearch.yml"

- name: Adjust Elasticsearch Heap Size to 50% of available RAM
  lineinfile:
    state: present
    dest: "/etc/init.d/elasticsearch"
    regexp: "#ES_HEAP_SIZE=2g"
    line: "ES_HEAP_SIZE={{ elasticsearch_heap_size }}"
  notify: Reload Service | elasticsearch
